/* Writes app/icon.svg: one frame of the wordmark's ball, as squares.
 *
 *   npm run icon
 *
 * The mark on the page is a canvas that has to be running to exist, and a
 * favicon is a file. So this takes the same geometry — lib/ball, the same
 * module the canvas calls sixty times a second — stops it at one angle, and
 * writes each cell out as a square instead of a character. Nothing here knows
 * anything about the ball; if the ball changes, run this again.
 *
 * The output is checked in, because the site is a static export and a build
 * that has to raycast a sphere to produce a favicon is a build with a sphere
 * raycaster in it.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { BANDS, RAMP, orient, sampleCell, seamWidth } from "../lib/ball.ts";

// Cells across the icon. Favicons are drawn at 16px and at exact multiples of
// it, so at 16 the grid lands on whole device pixels every time and the squares
// stay square — 20 would be sharper in principle and blurry in every tab. It is
// also about the floor for the seam: much coarser and the curve is stairs.
const N = 16;

// Which frame of the spin. The ball is only ever seen turning, so no angle is
// the canonical one, but held still they are not equally legible: for much of
// the turn the seam runs down one side, and a seam down one side at this size is
// a line down one side. Here it crosses the face and leaves at the silhouette at
// both ends, which is the shape that survives being sixteen pixels wide.
const ANGLE = Math.PI / 6;

// Block elements are cells with a coverage each; squares can just be that
// coverage. Index into RAMP, so the icon thins out exactly where the type does.
const COVERAGE = [1, 0.75, 0.5, 0.25];

const r = N / 2;
const o = orient(ANGLE);
const seamW = seamWidth(1, r);

// One group per colour and coverage, so the file is a dozen paths rather than
// 256 rectangles.
const groups = new Map<string, string[]>();

for (let j = 0; j < N; j++) {
  // Runs, not cells: a row of the body is one rectangle, and most rows are
  // nearly one run.
  let runStart = -1;
  let runKey = "";

  const flush = (end: number) => {
    if (runStart < 0) return;
    const w = end - runStart;
    const d = `M${runStart} ${j}h${w}v1h-${w}z`;
    const into = groups.get(runKey);
    if (into) into.push(d);
    else groups.set(runKey, [d]);
    runStart = -1;
  };

  for (let i = 0; i < N; i++) {
    const cell = sampleCell((i + 0.5 - r) / r, (j + 0.5 - r) / r, o, seamW);
    const key = cell
      ? `${cell.band}:${Math.round(cell.shade * (RAMP.length - 1))}`
      : "";

    if (key !== runKey) {
      flush(i);
      runKey = key;
      if (key) runStart = i;
    }
  }
  flush(N);
}

const paths = [...groups]
  .sort()
  .map(([key, ds]) => {
    const [band, level] = key.split(":").map(Number);
    const fill = BANDS[band].color;
    const alpha = COVERAGE[level];
    const opacity = alpha < 1 ? ` fill-opacity="${alpha}"` : "";
    return `  <path fill="${fill}"${opacity} d="${ds.join("")}"/>`;
  })
  .join("\n");

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${N} ${N}" shape-rendering="crispEdges">
  <!-- Generated by scripts/gen-icon.mts from lib/ball. Do not edit by hand. -->
${paths}
</svg>
`;

// One site, but two Next apps — the docs own their own basePath and so their
// own metadata, and a tab open on the docs would otherwise get the browser's
// blank page icon. Same bytes in both, written from here so they cannot drift.
const OUT = ["../app/icon.svg", "../../docs/app/icon.svg"];

for (const rel of OUT) {
  const out = fileURLToPath(new URL(rel, import.meta.url));
  writeFileSync(out, svg);
  console.log(out);
}
console.log(`${N}x${N}, ${groups.size} paths, ${svg.length} bytes`);
